INSERT INTO question (id, question, correctAnswer, wrongAnswer, category) VALUES
  (1, 'Existing as recently as 100,000 years ago, Gigantopithecus blacki is an extinct species what animal?', 'Ape', false, 'Animals'),
  (2, 'Which marine animal is the only known natural predator of the great white shark?', 'Orca (killer whale)', false, 'Animals'),
  (3, '“Dazzle” is a term used for a group of what type of animal?', 'Zebra', false, 'Animals'),
  (4, 'What semi-aquatic, egg laying mammal, is native to Australia and Tasmania?', 'Platypus (Ornithorhynchus anatinus)', false, 'Animals'),
  (5, 'Ambergris is a waxy substance that originates as a secretion from what aquatic animal?', 'Sperm whale', false, 'Animals'),
  (6, 'What is the term for a group of kangaroos?', 'Mob (troop) (court)', false, 'Animals'),
  (7, 'The process of making cow’s milk safe for human consumption is called what?', 'Pasteurization', false, 'Animals'),
  (8, 'Orcinus orca is the scientific name for which animal?', 'Killer whale', false, 'Animals'),
  (9, 'Which bird has eyes that are larger than its brain?', 'Ostrich', false, 'Animals'),
  (10, 'What is the only snake in the world that builds a nest for its eggs?', 'King Cobra', false, 'Animals'),
  (11, 'What is the only mammal born with horns?', 'Giraffe', false, 'Animals'),
  (12, 'What flightless bird is featured on New Zealand’s one dollar coin?', 'Kiwi', false, 'Animals'),
  (13, 'What was the name of cowboy star Roy Rogers’ palomino horse?', 'Trigger (Golden Cloud)', false, 'Animals'),
  (14, 'A wombat is a marsupial native to which country?', 'Australia', false, 'Animals'),
  (15, 'A “sounder” is the term used to refer to a group of what type of animal?', 'Wild swine (pigs) (boars)', false, 'Animals'),

  (16, 'What is the only state that can be typed on one row of keys on a QWERTY keyboard?', 'Alaska', false, 'Computers'),
  (17, 'What three-digit web error code for censored content is a reference to a Ray Bradbury novel?', '451', false, 'Computers'),
  (18, 'A modulator-demodulator is a hardware device better known as what?', 'Modem', false, 'Computers'),
  (19, 'What does the online acronym SMH stand for?', 'Shaking my head', false, 'Computers'),
  (20, 'The name of the popular online battle royale game PUBG, is short for what?', 'PlayerUnknown’s Battlegrounds', false, 'Computers'),
  (21, 'When referring to cables used to transmit audio/video, what does HDMI stand for?', 'High-Definition Multimedia Interface', false, 'Computers'),
  (22, 'What was the first publicly traded U.S. company to reach a $1 trillion market cap?', 'Apple', false, 'Computers'),
  (23, 'On the popular social website Reddit, what does AMA stand for?', 'Ask Me Anything', false, 'Computers'),
  (24, 'What do the letters CPU stand for when referring to the “brains” of a computer?', 'Central Processing Unit', false, 'Computers'),
  (25, 'On which popular website do users send tweets?', 'Twitter', false, 'Computers'),
  (26, 'SNES is the acronym for what popular gaming console released in the early 1990s?', 'Super Nintendo Entertainment System', false, 'Computers'),
  (27, 'Mark Zuckerberg was one of the founders of which social networking site?', 'Facebook', false, 'Computers'),
  (28, 'What was the first console video game that allowed the game to be saved?', 'The Legend of Zelda', false, 'Computers'),
  (29, 'Regarding data storage, what does the acronym SSD stand for?', 'Solid State Drive', false, 'Computers'),
  (30, 'The Connecticut Leather Company later became what toy company that was popular in the 1980s for its Cabbage Patch Kids and video game consoles?', 'Coleco', false, 'Computers'),

  (31, 'American politician and diplomat Madeleine Albright was born in what central European country?', 'Czechoslovakia', false, 'Politics'),
  (32, 'At the time of his assassination, what play was Abraham Lincoln watching?', 'Our American Cousin', false, 'Politics'),
  (33, 'Where was Richard Nixon when he delivered his infamous “I am not a crook” speech?', 'Disney World in Orlando, Florida (The Contemporary Resort)', false, 'Politics'),
  (34, 'In 1952, Albert Einstein was offered the presidency of which country?', 'Israel', false, 'Politics'),
  (35, 'Who was first U.S. president to be impeached?', 'Andrew Johnson', false, 'Politics'),
  (36, 'Who became both a vice president and president of the United States without ever being elected to either office?', 'Gerald Ford', false, 'Politics'),
  (37, 'Who was the first female Prime Minister of a European country?', 'Margaret Thatcher', false, 'Politics'),
  (38, 'Which U.S. president issued the Emancipation Proclamation?', 'Abraham Lincoln', false, 'Politics'),
  (39, 'The Bill of Rights contains how many of the first amendments to the United States Constitution?', 'Ten (10)', false, 'Politics'),
  (40, 'Who was the first U.S. president that was born a citizen of the United States?', 'Martin van Buren', false, 'Politics'),
  (41, 'Who won the nomination of the Democratic Party to run for president in 2016?', 'Hillary Clinton', false, 'Politics'),
  (42, 'Who was the vice president that served under President Barack Obama?', 'Joe Biden', false, 'Politics'),
  (43, 'What late American singer was the mayor of Palm Springs California from 1988 to 1992?', 'Sonny Bono', false, 'Politics'),
  (44, 'Who was vice president of the United States when Lincoln was assassinated?', 'Andrew Johnson', false, 'Politics'),
  (45, 'Who is the oldest person to be elected to the office of President of the United States?', 'Donald Trump (Trump)', false, 'Politics'),

  (46, 'What is the only Canadian province without a natural border?', 'Saskatchewan', false, 'Geography'),
  (47, '“Oro y Plata” (Spanish for gold and silver) is the motto of which U.S. state?', 'Montana', false, 'Geography'),
  (48, 'What country is home to the longest canal in the world?', 'China (Beijing-Hangzhou Grand Canal)', false, 'Geography'),
  (49, 'The Nation of Brunei is located on the north coast of which island?', 'Borneo', false, 'Geography'),
  (50, 'Located approximately halfway between Iceland and Norway, the Faroe Islands are a territory of which country?', 'Denmark', false, 'Geography'),
  (51, 'What is the only U.S. state home to a real royal palace once used by a monarchy?', 'Hawaii', false, 'Geography'),
  (52, 'Currently a popular tourist destination, which Croatian city is known as “The Pearl of the Adriatic”?', 'Dubrovnik', false, 'Geography'),
  (53, 'In 1862, the city of Bucharest became the capital of which country?', 'Romania', false, 'Geography'),
  (54, 'From which major U.S. city can a person drive south into Canada?', 'Detroit', false, 'Geography'),
  (55, 'By volume, what is the largest body of water in the United Kingdom?', 'Loch Ness', false, 'Geography'),
  (56, 'What “fashion capital” city is home to Dolce & Gabbana, Prada, and Versace?', 'Milan (Milano)', false, 'Geography'),
  (57, 'What Los Angeles landmark was named after a World War II general and inspired a Donna Summer disco hit?', 'MacArthur Park', false, 'Geography'),
  (58, 'With a latitude of 41° 17′ South, what is the southernmost capital city in the world?', 'Wellington, New Zealand', false, 'Geography'),
  (59, 'The Equator passes through which three countries in South America?', 'Ecuador, Colombia & Brazil', false, 'Geography'),
  (60, 'What Canadian province separates Alaska from the continental United States?', 'British Columbia', false, 'Geography');